### ISSUE TITLE
метод cleaner вызывает эксепшн

### ISSUE THREAD

**Issue by dis-aster** [Prototype-X/blacklist-rkn-tool#5]
вызов метода
```
        if self.check_diff():
            self.cleaner()
            return 1
```
приводит к 
`pymysql.err.NotSupportedError: (1235, "This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'")`

**Comment by Prototype-X** [comment]
Приветствую. В данном случае это ограничение движка БД, возможно это вылечится установкой свежей версии MariaDB/MySQL. Замечу, что у SQLite/PostgreSQL таких проблем нет. Работоспособность последних версий тестировалась на SQLite/PostgreSQL. Допускаю что это возможно не единственное место в коде, где придется столкнуться с ограничениями движка БД MariaDB/MySQL, поскольку SQL запросы стали более сложными из-за добавления новых возможностей. Рекомендую воспользоваться SQLite/PostgreSQL.

**Comment by dis-aster** [comment]
Добрый день.
К сожалению, обновлением софта это не решится, так как limit в subquery не поддерживается ни в MySQL, ни в MariaDB, ни в Percona-server: https://dev.mysql.com/doc/refman/5.6/en/subquery-restrictions.html
Спасибо, учту вашу рекомендацию.

**Comment by Prototype-X** [comment]
MySQL больше не поддерживается
